name: Release commit
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      # - run: npm test
  create-release-commit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci
      - name: Initalize git user email
        run: git config --global user.email "${{vars.RELEASE_USER_EMAIL}}"
      - name: Initalize git user name
        run: git config --global user.name "Release commit workflow"

      - name: Create release branch and set upstream
        id: release
        run: |
          BRANCH="release-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $BRANCH
          git push --set-upstream origin $BRANCH
          echo "::set-output name=branch::$BRANCH"

      - name: Bump version and push changes using release-it
        run: npm run release -- --ci ${{github.event.release.tag_name}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Push changes to release branch
        run: |
          git push origin ${{ steps.release.outputs.branch }}
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.release.outputs.branch }}
          base: main
          title: "Release $(date +'%Y-%m-%d %H:%M:%S')"
          body: "Automated release of version $(date +'%Y-%m-%d %H:%M:%S')"
          draft: false
