name: Release commit
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Create release branch and bump version
        id: release
        run: |
          BRANCH="release-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $BRANCH
          npx release-it --ci
          echo "::set-output name=branch::$BRANCH"

      - name: Push changes to release branch
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git push origin ${{ steps.release.outputs.branch }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.release.outputs.branch }}
          base: main
          title: "Release $(date +'%Y-%m-%d %H:%M:%S')"
          body: "Automated release of version $(date +'%Y-%m-%d %H:%M:%S')"
          draft: false