name: Fetch Latest Release Info
on: [push]

jobs:
  fetch-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch latest release info
        run: |
          RELEASE_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases")

          if [ $? -ne 0 ]; then
            echo "Failed to fetch releases"
            exit 1
          fi

          LATEST_RELEASE_NAME=$(echo "$RELEASE_JSON" | jq -r '.[0].name')
          IS_PRE_RELEASE=$(echo "$RELEASE_JSON" | jq -r '.[0].prerelease')

          echo "Latest release name: $LATEST_RELEASE_NAME"
          echo "Is pre-release: $IS_PRE_RELEASE"

          echo "LATEST_RELEASE_NAME=$LATEST_RELEASE_NAME" >> $GITHUB_ENV
          echo "IS_PRE_RELEASE=$IS_PRE_RELEASE" >> $GITHUB_ENV
