name: Node.js CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get release info
        id: release
        run: |
          RELEASE_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest")

          LATEST_RELEASE_NAME=$(echo "$RELEASE_JSON" | jq -r '.name')
          IS_LATEST=$(echo "$RELEASE_JSON" | jq -r '.prerelease')

          echo "Latest release name: $LATEST_RELEASE_NAME"
          echo "Is latest release: $IS_LATEST"
